### ISSUE TITLE
virtual sensor database table does not change to match new structure

### ISSUE THREAD

**Issue by charvolant** [OpenIotOrg/openiot#48]
If I add an additional field to a virtual sensor, the h2 database table is unhappy.

ERROR [2014-01-30 12:11:18,460] gsn.VSensorLoader [VSensorLoader-Thread0](VSensorLoader.java:127)     - The table kirkegaardanddanishrevenuec03r01ungrazedhighngbheavy100 in the database, doesn't have the >depth< column.
org.openiot.gsn.utils.GSNRuntimeException: The table kirkegaardanddanishrevenuec03r01ungrazedhighngbheavy100 in the database, doesn't have the >depth< column.
        at org.openiot.gsn.storage.StorageManager.tableExists(StorageManager.java:238)
        at org.openiot.gsn.storage.StorageManager.tableExists(StorageManager.java:261)
        at org.openiot.gsn.VSensorLoader.loadPlugin(VSensorLoader.java:215)
        at org.openiot.gsn.VSensorLoader.loadPlugin(VSensorLoader.java:170)
        at org.openiot.gsn.VSensorLoader.run(VSensorLoader.java:125)
        at java.lang.Thread.run(Thread.java:744)

A simple workaround is to delete the database and allow it to regenerate.

**Comment by sarni** [comment]
GSN doesn't support dynamic changes in virtual sensor fields (additions, deletions, changes of types). Adding such a feature can lead to side effects as virtual sensor structure is assumed to be static. One can think about a tool for editing/recycling virtual sensors. This tool should guarantee the consistency of both the schema and the data (including historical) in the database.

**Comment by nkef** [comment]
Could be forwarded to GSN community
