### ISSUE TITLE
Unable to Register or login in Ide.core

### ISSUE THREAD

**Issue by ghost** [OpenIotOrg/openiot#57]
Hi, 

When trying to Register in ide.core, it gives a error message as "An account with supplied Email Account already exist". Tried several times with different email accounts but still gives the same error. Kindly help.

Thanks.
![openiot](https://f.cloud.github.com/assets/6735125/2434222/68e52aba-adad-11e3-8109-8a785fb67efa.jpg)

**Comment by premjayaraman** [comment]
Hi,  Could you look at the JBOSS container and reports the errors logged?

By JBOSS container I mean, the JBOSS server running in your command line/terminal. That should have a list of errors after you click the register button.

thanks

**Comment by ghost** [comment]
This is the error I got after deploying & trying to register....
17:38:06,119 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/scheduler.core].[org.openiot.scheduler.core.rest.JaxRsActivator]](http--127.0.0.1-8080-7) Servlet.service() for servlet org.openiot.scheduler.core.rest.JaxRsActivator threw exception: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: endpoint URL may not be null.
    at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:340) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:214) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:190) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:540) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.2.Final.jar:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206) [javamelody-core-1.45.0.jar:1.45.0]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:179) [javamelody-core-1.45.0.jar:1.45.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]
Caused by: java.lang.IllegalArgumentException: endpoint URL may not be null.
    at org.openrdf.repository.sparql.SPARQLRepository.<init>(SPARQLRepository.java:74) [sesame-repository-sparql-2.7.0.jar:]
    at org.openrdf.repository.sparql.SPARQLRepository.<init>(SPARQLRepository.java:58) [sesame-repository-sparql-2.7.0.jar:]
    at org.openiot.scheduler.core.utils.sparql.SesameSPARQLClient.<init>(SesameSPARQLClient.java:51) [classes:]
    at org.openiot.scheduler.core.api.impl.UserRegister.UserRegisterImpl.registerUser(UserRegisterImpl.java:92) [classes:]
    at org.openiot.scheduler.core.api.impl.UserRegister.UserRegisterImpl.<init>(UserRegisterImpl.java:79) [classes:]
    at org.openiot.scheduler.core.rest.SchedulerRsControler.userRegister(SchedulerRsControler.java:142) [classes:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_45]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_45]
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:155) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525) [resteasy-jaxrs-2.3.2.Final.jar:]
    ... 23 more

**Comment by nkef** [comment]
Hi,

Thank you for using OpenIoT and reporting this error. Could you please provide your "[openiot.properties](https://github.com/OpenIotOrg/openiot/wiki/Openiot-Commons-Library)" file you are using. Moreover please move this thread to the "[openiot-dev](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists)" mailing list till we identify the problem since in the issue section we list identified problems/issues.

Best Regards,

Nikos Kefalakis.

**Comment by mrsaniat** [comment]
I have the same issue: Cant login to openiot using local instance of lsm-light.

**Comment by hylkevds** [comment]
Can you check the configuration file jboss/standalone/configuration/openiot.properties ?
I suspect it points to the LSM instance running at DERI and not at your local instance.

**Comment by mrsaniat** [comment]
I have configured my openiot.properties file in the jboss directory like this:

https://docs.google.com/file/d/0B6fEpfpblobQQXNJTGticnlOcmc/edit?pli=1

This instruction is from the github:
https://github.com/OpenIotOrg/openiot/wiki/Sensor-Data-Develop

**Comment by hylkevds** [comment]
Ah, I see, that contains a wrong port for lsm.remote.server.
lsm.remote.server should point to LSM-Light running in jboss (probably on port 8080) while lsm.sparql.endpoint should point to the virtuoso endpoint at port 8890
Those two can not run at the same port...

So the documentation contains an error.

**Comment by nkef** [comment]
moved this documentation error in [issue 63](https://github.com/OpenIotOrg/openiot/issues/63) because in this issue the request/error is not clearly identified.

**Comment by hylkevds** [comment]
I'm pretty sure the original problem was also caused by an mis-configured openiot.properties file. Since the error contained:

```
Caused by: java.lang.IllegalArgumentException: endpoint URL may not be null.
at org.openrdf.repository.sparql.SPARQLRepository.(SPARQLRepository.java:74) [sesame-repository-sparql-2.7.0.jar:]
```

I guess the side issue of a wrong/unhelpful error appearing ("email already exists" instead of "can't connect to LSM") isn't relevant any more as soon as the security integration is finished.

**Comment by nmqhoan** [comment]
You're right. I think the problem is only mis-configured openiot.properties file, as I could see in https://docs.google.com/file/d/0B6fEpfpblobQQXNJTGticnlOcmc/edit?pli=1. LSM LIGHT is deployed on JBOSS so the correct one is: http://localhost:8080/lsm-light.server

**Comment by mrsaniat** [comment]
Hi All,
The attached openiot.properties file worked perfectly with the local
instance of lsm-light server and client. Worth to mention, the present
properties file in github points to deri-lsm. So if someone wants to run a
local standalone instance of openiot, he always have to modify the
properties.

It might be better if you place this version in the github. In that case no
modification is needed.

---

#Scheduler Properties

scheduler.core.lsm.openiotMetaGraph=http://lsm.deri.ie/OpenIoT/demo/sensormeta#
scheduler.core.lsm.openiotDataGraph=http://lsm.deri.ie/OpenIoT/demo/sensordata#
scheduler.core.lsm.openiotFunctionalGraph=http://lsm.deri.ie/OpenIoT/demo/functionaldata#
scheduler.core.lsm.access.username=openiot_guest
scheduler.core.lsm.access.password=openiot
scheduler.core.lsm.sparql.endpoint=http://localhost:8890/sparql
scheduler.core.lsm.remote.server=http://localhost:8080/lsm-light.server/

#Service Delivery & Utility Manager (SD&UM) Properties

sdum.core.lsm.openiotFunctionalGraph=http://lsm.deri.ie/OpenIoT/demo/functionaldata#
sdum.core.lsm.sparql.endpoint=http://localhost:8890/sparql
sdum.core.lsm.remote.server=http://localhost:8080/lsm-light.server/

#Request Definition

#Request Presentation

#LSM-LIGHT Properties
lsm-light.server.connection.driver_class=virtuoso.jdbc4.Driver
lsm-light.server.connection.url=jdbc:virtuoso://localhost:1111/log_enable=2

lsm-light.server.connection.username=dba
lsm-light.server.connection.password=dba
lsm-light.server.minConnection=10
lsm-light.server.maxConnection=15
lsm-light.server.acquireRetryAttempts=5
#for local virtuoso instance
lsm-light.server.localMetaGraph = http://lsm.deri.ie/OpenIoT/demo/sensormeta#

## lsm-light.server.localDataGraph = http://lsm.deri.ie/OpenIoT/demo/sensordata#

Thanks a lot.

Regards

On Fri, Apr 25, 2014 at 3:49 PM, nmqhoan notifications@github.com wrote:

> You're right. I think the problem is only mis-configured
> openiot.properties file, as I could see in
> https://docs.google.com/file/d/0B6fEpfpblobQQXNJTGticnlOcmc/edit?pli=1.
> LSM LIGHT is deployed on JBOSS so the correct one is:
> http://localhost:8080/lsm-light.server
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/OpenIotOrg/openiot/issues/57#issuecomment-41400890
> .

## 

Saniat
Erasmus Mundus IMSE Student
