### ISSUE TITLE
Scheduler Error

### ISSUE THREAD

**Issue by keithsptr** [OpenIotOrg/openiot#72]
Hi,

I have updated the OpenIoT Platform to the new one there is in github but however when I try to discover sensors from the platform it gives me a message in terminal saying Error communicating with schedulerr (method discoverSensors, HTTP error code : 500).

I have everything uploaded in Jboss as you can see below and is running. If you type 92.251.103.22:1098/scheduler.core/rest/services you will see that scheduler is there.

if you type http://92.251.103.22:1098/lsm-light.server/ it gives you the message: Welcome to OpenIoT's version of LSM!

![image](https://cloud.githubusercontent.com/assets/3962994/3853806/84d263f6-1ecc-11e4-9fc4-295d5d02b819.png)

![jboss](https://cloud.githubusercontent.com/assets/3962994/3853798/5c104028-1ecc-11e4-9162-64e7ca50bd21.png)

**Comment by hylkevds** [comment]
Which branch from github did you check out?

Is there anything in the jboss log file? There should be an exception listed there.

Also, you should not deploy any of the jar files. Only the war files/web projects should be deployed on jboss.

**Comment by keithsptr** [comment]
I have checked out the develop branch.

Re the log file where can I find it please because I only see the terminal. The error I see in terminal is

10:22:04,306 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/scheduler.core].[org.openiot.scheduler.core.rest.JaxRsActivator]](http--192.168.0.37-1098-1) Servlet.service() for servlet org.openiot.scheduler.core.rest.JaxRsActivator threw exception: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
    at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:340) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:214) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:190) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:540) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.2.Final.jar:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206) [javamelody-core-1.45.0.jar:1.45.0]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:179) [javamelody-core-1.45.0.jar:1.45.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
    at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:415) [slf4j-log4j12-1.5.8.jar:1.5.8]
    at org.openrdf.http.client.HTTPClient.getErrorInfo(HTTPClient.java:1003) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:935) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.sendTupleQueryViaHttp(HTTPClient.java:709) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.getBackgroundTupleQueryResult(HTTPClient.java:593) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.sendTupleQuery(HTTPClient.java:358) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:54) [sesame-repository-sparql-2.7.0.jar:]
    at org.openiot.scheduler.core.utils.sparql.SesameSPARQLClient.sparqlToQResult(SesameSPARQLClient.java:108) [classes:]
    at org.openiot.scheduler.core.api.impl.DiscoverSensors.DiscoverSensorsImpl.discoversensors(DiscoverSensorsImpl.java:229) [classes:]
    at org.openiot.scheduler.core.api.impl.DiscoverSensors.DiscoverSensorsImpl.<init>(DiscoverSensorsImpl.java:205) [classes:]
    at org.openiot.scheduler.core.rest.SchedulerRsControler.discoverSensors(SchedulerRsControler.java:179) [classes:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_51]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_51]
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:155) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525) [resteasy-jaxrs-2.3.2.Final.jar:]
    ... 23 more

10:22:04,384 SEVERE [org.openiot.ui.request.commons.logging.LoggerService](http--192.168.0.37-1098-2) OpenIoT:RequestDefinition: [SEVERE] [SchedulerAPIWrapper.java:76] org.openiot.ui.request.commons.providers.exceptions.APICommunicationException: Error communicating with schedulerr (method: discoverSensors, HTTP error code : 500)

Re jar files I will remove. 

Thanks

**Comment by hylkevds** [comment]
Odd, seems like a version conflict in the logger. Can you clean & build everything?
You should be able to give the commands:
mvn clean
mvn install
At the top of the github project. That should re-build everything.

**Comment by keithsptr** [comment]
Ok will do that and get back to you.

**Comment by keithsptr** [comment]
Now the error is different when I did mvn clean and mvn install

13:17:59,942 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/scheduler.core].[org.openiot.scheduler.core.rest.JaxRsActivator]](http--192.168.0.37-1098-3) Servlet.service() for servlet org.openiot.scheduler.core.rest.JaxRsActivator threw exception: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
    at org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:340) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:214) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:190) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:540) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.2.Final.jar:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206) [javamelody-core-1.45.0.jar:1.45.0]
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:179) [javamelody-core-1.45.0.jar:1.45.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_51]
Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
    at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:415) [slf4j-log4j12-1.5.8.jar:1.5.8]
    at org.openrdf.http.client.HTTPClient.getErrorInfo(HTTPClient.java:1003) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:935) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.sendTupleQueryViaHttp(HTTPClient.java:709) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.getBackgroundTupleQueryResult(HTTPClient.java:593) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.http.client.HTTPClient.sendTupleQuery(HTTPClient.java:358) [sesame-http-client-2.7.0.jar:]
    at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:54) [sesame-repository-sparql-2.7.0.jar:]
    at org.openiot.scheduler.core.utils.sparql.SesameSPARQLClient.sparqlToQResult(SesameSPARQLClient.java:108) [classes:]
    at org.openiot.scheduler.core.api.impl.DiscoverSensors.DiscoverSensorsImpl.discoversensors(DiscoverSensorsImpl.java:229) [classes:]
    at org.openiot.scheduler.core.api.impl.DiscoverSensors.DiscoverSensorsImpl.<init>(DiscoverSensorsImpl.java:205) [classes:]
    at org.openiot.scheduler.core.rest.SchedulerRsControler.discoverSensors(SchedulerRsControler.java:179) [classes:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_51]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_51]
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:155) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211) [resteasy-jaxrs-2.3.2.Final.jar:]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525) [resteasy-jaxrs-2.3.2.Final.jar:]
    ... 23 more

13:18:00,002 SEVERE [org.openiot.ui.request.commons.logging.LoggerService](http--192.168.0.37-1098-1) OpenIoT:RequestDefinition: [SEVERE] [SchedulerAPIWrapper.java:72] java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.

**Comment by hylkevds** [comment]
Did you re-deploy all the components with the newly compiled version?

**Comment by keithsptr** [comment]
Yes. I downloaded them again... did mvn clean and mvn install. And now I cannot log in. I don't know what it happening.. Do someone have the old version please because with this I won't work

**Comment by hylkevds** [comment]
Can you:
1. undeploy overything from jboss
2. Double check to make sure everything is undeployed
3. Deploy the modules one by one, in the order:
3.1. LSM-Light server
3.2. Scheduler Core
3.3. sdum.core
3.4. request definition web app
3.5. request presentation web app
And after every single one, check for exceptions in the log file.

Since it seems the re-deploy did not go as it should have.

**Comment by keithsptr** [comment]
I did that several times with no outcome :(

**Comment by hylkevds** [comment]
So after which deployment did you get this error?
Since the last error is about a connection that was not freed, did you try restarting jboss, or even the machine?

**Comment by nkef** [comment]
I am closing this thread since it seems there is no more feedback (For arbitrary unidentified issues please use the [mailing list](https://github.com/OpenIotOrg/openiot/wiki/Mailing-Lists)).
