### ISSUE TITLE
SecurityIntegration: XGSN can't push data

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#78]
Registering the sensor seems to work fine (no obvious errors) but when trying to push data I get the following exception.
Notice that the error names the field `FIELD1` in capitals, though the field is called `field1` in non-capitals.

```
11:18:18.794 [VSensorLoader-Thread0] DEBUG o.o.g.metadata.LSM.LSMSensorMetaData - Read file /home/scf/NetBeansProjects/OpenIoT/OpenIotSecurity/OpenIotOrg/modules/x-gsn/virtual-sensors/testsensor1.metadata
11:18:18.796 [VSensorLoader-Thread0] INFO  o.o.g.metadata.LSM.LSMSensorMetaData - 0 : field1
11:18:36.278 [  NioProcessor-2] DEBUG o.o.g.w.t.SingletonTcpListenWrapper - Sensor 0.816467, Queueing: {field1=2484.0}
11:18:36.279 [SingletonTcpListenWrapper-Thread-1] DEBUG o.o.g.w.t.SingletonTcpListenWrapper - Sensor 0.816467, forwarding data.
ERROR [2014-08-18 11:18:36,348] [SingletonTcpListenWrapper-Thread-1] (AbstractWrapper.java:255)     - The field FIELD1 in virtual sensor testsensor1 has no associated metadata. PropertyUri: http://openiot.eu/OpenIoT/Random1
java.lang.IllegalArgumentException: The field FIELD1 in virtual sensor testsensor1 has no associated metadata. PropertyUri: http://openiot.eu/OpenIoT/Random1
    at org.openiot.gsn.metadata.LSM.SensorAnnotator.updateSensorDataOnLSM(SensorAnnotator.java:126)
    at org.openiot.gsn.vsensor.LSMExporter.dataAvailable(LSMExporter.java:118)
    at org.openiot.gsn.beans.InputStream.executeQuery(InputStream.java:300)
    at org.openiot.gsn.beans.StreamSource.windowSlided(StreamSource.java:349)
    at org.openiot.gsn.beans.windowing.SQLViewQueryRewriter.dataAvailable(SQLViewQueryRewriter.java:107)
    at org.openiot.gsn.beans.windowing.TupleBasedSlidingHandler.dataAvailable(TupleBasedSlidingHandler.java:80)
    at org.openiot.gsn.wrappers.AbstractWrapper.postStreamElement(AbstractWrapper.java:245)
    at org.openiot.gsn.wrappers.tcplistener.SingletonTcpListenWrapper.forwardData(SingletonTcpListenWrapper.java:162)
    at org.openiot.gsn.wrappers.tcplistener.SingletonTcpListenWrapper.run(SingletonTcpListenWrapper.java:116)
ERROR [2014-08-18 11:18:36,350] [SingletonTcpListenWrapper-Thread-1] (AbstractWrapper.java:256)     - Produced data item from the wrapper couldn't be propagated inside the system.
11:18:36.350 [SingletonTcpListenWrapper-Thread-1] DEBUG o.o.g.w.t.SingletonTcpListenWrapper - Sensor 0.816467, success: false, queue: 0.
```

```
information="A generated sensor"
sourceType=lausanne
field {
    field1 {
        propertyName="http://openiot.eu/OpenIoT/Random1"
        unit=Percent
    }
}
author=FraunhoferIOSB
source="http://openiot.eu"
sensorID="http://openiot.eu/resource/36447359194485"
sensorType=testType
longitude=6.596818
feature="http://lsm.deri.ie/OpenIoT/opensensefeature"
latitude=46.529838
sensorName="opensense_1"
fields=field1
```

```
<virtual-sensor name="testsensor1" priority="10" publish-to-lsm="true">
   <processing-class>
      <class-name>org.openiot.gsn.vsensor.LSMExporter</class-name>
      <init-params>
          <param name='allow-nulls'>false</param>
          <param name='publish-to-lsm'>true</param>
      </init-params>
      <web-input>
        <command name="cmd1">
             <field name="field1" type="int">field1</field>
        </command>
      </web-input>
      <output-structure>
         <field name="field1" type="int" />
      </output-structure>
   </processing-class>
   <life-cycle pool-size="100" />
   <addressing />
   <storage history-size="2h" />
   <streams>
      <stream name="input1">
         <source alias="source1" sampling-rate="1" storage-size="1">
            <address wrapper="singletontcp">
               <predicate key="fields">field1</predicate>
               <predicate key="formats">numeric</predicate>
               <predicate key="bad-values">NaN,null</predicate>
               <predicate key="timezone">Etc/GMT-2</predicate>
               <predicate key="port">22002</predicate>
               <predicate key="id">0.816467</predicate>
            </address>
            <query>select * from wrapper</query>
         </source>
         <query>select * from source1</query>
      </stream>
   </streams>
</virtual-sensor>
```

**Comment by hylkevds** [comment]
I've tried adding the property to the output structure in the XML file, like in the opensense_1.xml example, but that didn't work. It would also be duplication of settings, which would be bad.

**Comment by hylkevds** [comment]
I just noticed I had put the property field into the web-input part instead of the output-structure. Alas, after moving it to the right spot it still gives the same error. Here with a bit more debug output:

```
6:01:26.704 [VSensorLoader-Thread0] WARN  org.openiot.gsn.VSensorLoader - adding : testsensor1 virtual sensor[/home/scf/NetBeansProjects/OpenIoT/OpenIotSecurity/OpenIotOrg/modules/x-gsn/virtual-sensors/testsensor1.xml]
16:01:26.704 [VSensorLoader-Thread0] DEBUG o.o.g.metadata.LSM.LSMSensorMetaData - Read file /home/scf/NetBeansProjects/OpenIoT/OpenIotSecurity/OpenIotOrg/modules/x-gsn/virtual-sensors/testsensor1.metadata
16:01:26.706 [VSensorLoader-Thread0] INFO  o.o.g.metadata.LSM.LSMSensorMetaData - 0 : field1
16:01:26.706 [VSensorLoader-Thread0] INFO  org.openiot.gsn.vsensor.LSMExporter - Sensor has 1 outputfields.
16:01:26.706 [VSensorLoader-Thread0] INFO  org.openiot.gsn.vsensor.LSMExporter - Property:field1--http://openiot.eu/OpenIoT/Random1
16:01:26.707 [VSensorLoader-Thread0] INFO  org.openiot.gsn.vsensor.LSMExporter - Allow nulls => false
16:01:26.707 [VSensorLoader-Thread0] INFO  org.openiot.gsn.vsensor.LSMExporter - field1
16:01:26.707 [VSensorLoader-Thread0] DEBUG org.openiot.gsn.VirtualSensor - Created a new instance for VS testsensor1
16:01:43.029 [SingletonTcpListenWrapper-Thread-3] DEBUG org.openiot.gsn.vsensor.LSMExporter - FIELD1 : t=Mon Aug 18 16:01:42 CEST 2014 v=3498.0
16:01:43.030 [SingletonTcpListenWrapper-Thread-3] DEBUG org.openiot.gsn.VirtualSensor - Enforcing the limit size on the VS table by : delete from testsensor1 where testsensor1.timed < 0 - 7200000
16:01:43.032 [SingletonTcpListenWrapper-Thread-3] DEBUG org.openiot.gsn.VirtualSensor - 0 old rows dropped from testsensor1
16:01:43.033 [SingletonTcpListenWrapper-Thread-3] ERROR o.o.gsn.wrappers.AbstractWrapper - The field FIELD1 in virtual sensor testsensor1 has no associated metadata. PropertyUri: http://openiot.eu/OpenIoT/Random1
java.lang.IllegalArgumentException: The field FIELD1 in virtual sensor testsensor1 has no associated metadata. PropertyUri: http://openiot.eu/OpenIoT/Random1
    at org.openiot.gsn.metadata.LSM.SensorAnnotator.updateSensorDataOnLSM(SensorAnnotator.java:126) ~[classes/:na]
    at org.openiot.gsn.vsensor.LSMExporter.dataAvailable(LSMExporter.java:119) ~[classes/:na]
    at org.openiot.gsn.beans.InputStream.executeQuery(InputStream.java:300) ~[classes/:na]
    at org.openiot.gsn.beans.StreamSource.windowSlided(StreamSource.java:349) ~[classes/:na]
    at org.openiot.gsn.beans.windowing.SQLViewQueryRewriter.dataAvailable(SQLViewQueryRewriter.java:107) ~[classes/:na]
    at org.openiot.gsn.beans.windowing.TupleBasedSlidingHandler.dataAvailable(TupleBasedSlidingHandler.java:80) ~[classes/:na]
    at org.openiot.gsn.wrappers.AbstractWrapper.postStreamElement(AbstractWrapper.java:245) ~[classes/:na]
    at org.openiot.gsn.wrappers.tcplistener.SingletonTcpListenWrapper.forwardData(SingletonTcpListenWrapper.java:162) [GSNTcpListenWrapper-1.0-SNAPSHOT.jar:na]
    at org.openiot.gsn.wrappers.tcplistener.SingletonTcpListenWrapper.run(SingletonTcpListenWrapper.java:116) [GSNTcpListenWrapper-1.0-SNAPSHOT.jar:na]
16:01:43.033 [SingletonTcpListenWrapper-Thread-3] ERROR o.o.gsn.wrappers.AbstractWrapper - Produced data item from the wrapper couldn't be propagated inside the system.
```

**Comment by jpcik** [comment]
Bug loading the filed names (there is a map of field names and observed properties which was wrong in some cases).

**Comment by hylkevds** [comment]
Ok, so do we still need the field annotation in both files, or is having it in just the metadata file enough?

**Comment by jpcik** [comment]
In the metadata is enough.
