### ISSUE TITLE
Sensor Schema Editor: Sensor types not listed

### ISSUE THREAD

**Issue by hylkevds** [OpenIotOrg/openiot#94]
I've just created a Sensor Type, but it is not listed in the sensor instance editor. The dropdown box is empty. The ontology does contain the sensor type, so the registration of the type seems to have worked fine.

Clicking "Clear Session/Restart" gives exceptions:

```
10:19:50,288 ERROR [stderr] (http--127.0.0.1-8080-36) org.openrdf.query.QueryInterruptedException
10:19:50,289 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openrdf.http.client.HTTPClient.handleHTTPError(HTTPClient.java:932)
10:19:50,290 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openrdf.http.client.HTTPClient.sendTupleQueryViaHttp(HTTPClient.java:709)
10:19:50,290 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openrdf.http.client.HTTPClient.getBackgroundTupleQueryResult(HTTPClient.java:593)
10:19:50,290 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openrdf.http.client.HTTPClient.sendTupleQuery(HTTPClient.java:358)
10:19:50,291 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openrdf.repository.sparql.query.SPARQLTupleQuery.evaluate(SPARQLTupleQuery.java:54)
10:19:50,291 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openiot.ui.sensorschema.utils.SesameSPARQLClient.sparqlToQResult(SesameSPARQLClient.java:125)
10:19:50,291 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openiot.ui.sensorschema.register.SensorRegistrarLSM.getSensorList(SensorRegistrarLSM.java:211)
```

``````
10:19:50,321 ERROR [stderr] (http--127.0.0.1-8080-36) java.lang.NullPointerException
10:19:50,322 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openiot.ui.sensorschema.register.SensorRegistrarLSM.getSensorList(SensorRegistrarLSM.java:212)
10:19:50,322 ERROR [stderr] (http--127.0.0.1-8080-36)   at org.openiot.ui.sensorschema.bean.SensorInstanceCreatorBean.init(SensorInstanceCreatorBean.java:93)```
``````

**Comment by hylkevds** [comment]
After some debugging I've found out that sesame is trying to use my proxy even though I've set -Dhttp.nonProxyHosts="localhost"

Any clue how to make it not use the proxy for localhost?
